joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30

shoulder_joint_controller: 
  type: "position_controllers/JointPositionController"
  joint: shoulder_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

foreArm_joint_controller: 
  type: "position_controllers/JointPositionController"
  joint: foreArm_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

upperArm_joint_controller: 
  type: "position_controllers/JointPositionController"
  joint: upperArm_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
  
wrist1_joint_controller: 
  type: "position_controllers/JointPositionController"
  joint: wrist1_joint
  pid: {p: 100.0, i: 0.01, d: 0.0}
  
wrist2_joint_controller: 
  type: "position_controllers/JointPositionController"
  joint: wrist2_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
  
wrist3_joint_controller: 
  type: "position_controllers/JointPositionController"
  joint: wrist3_joint
  pid: {p: 50.0, i: 0.01, d: 0.0}
